apiVersion: v2
name: mongodb
version: 1.0.0
description: A Helm chart for MongoDB
type: application

dependencies:
  - name: mongodb
    version: "16.4.0"
    repository: "https://charts.bitnami.com/bitnami"