container:
  image: postgres:15.2-alpine
  env:
    user: admin
    password: "secure-password"
    db: auth-db


# Enable persistence to store data
persistence:
  enabled: true
  storageClass: "standard"
  size: 10Gi

# Resources for the PostgreSQL container
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Node selector, tolerations, and affinity for advanced scheduling
nodeSelector: {}

tolerations: []

affinity: {}

# Liveness and readiness probes
livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5

readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5


env:
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  POSTGRES_DB: mydatabase

service:
  type: NodePort
  port: 5432
  nodeport: 30003


