version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin      # Set a custom username
      - RABBITMQ_DEFAULT_PASS=securepassword # Set a strong password
      - RABBITMQ_ERLANG_COOKIE=secretcookie  # Use a secret Erlang cookie for clustering
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persist RabbitMQ data
      - rabbitmq_logs:/var/log/rabbitmq  # Persist RabbitMQ logs
    ports:
      - "5672:5672"  # AMQP port for clients  
      - "15672:15672" # Management UI   "http://localhost:15672/""
    networks:
      - rabbitmq_network
    restart: always  # Automatically restart the container on failure or reboot

volumes:
  rabbitmq_data:   # Volume for RabbitMQ data
  rabbitmq_logs:   # Volume for RabbitMQ logs

networks:
  rabbitmq_network:
    driver: bridge  # Default network driver; you can configure as needed
