apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql-secrets
type: Opaque
data:
  POSTGRES_USER: {{ .Values.env.POSTGRES_USER | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.env.POSTGRES_PASSWORD | b64enc }}
  POSTGRES_DB: {{ .Values.env.POSTGRES_DB | b64enc }}