apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: postgres-service
    app: auth-app
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5432
      nodePort: {{ .Values.service.nodeport }}
  selector:
    app: postgres-prod
    app: auth-app

