apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-configmap
data:
  RABBITMQ_HOST: rabbitmq-service
  RABBITMQ_USER: admin
  RABBITMQ_PORT: "5672"
  RABBITMQ_PASSWORD: securepassword
  LOG_LEVEL: INFO
