piVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mongodb-config
  labels:
    app: mongodb
    release: {{ .Release.Name }}
data:
  mongodb.conf: |
    storage:
      dbPath: /data/db
    net:
      bindIp: 0.0.0.0
      port: 27017
    replication:
      oplogSizeMB: 50
      replSetName: rs0
