apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-data
  labels:
    app: mongodb
    release: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
      requests:
        storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}