apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongodb-secret
  labels:
    app: mongodb
    release: {{ .Release.Name }}
type: Opaque
data:
  rootUsername: {{ .Values.auth.rootUsername | b64enc | quote }}
  rootPassword: {{ .Values.auth.rootPassword | b64enc | quote }}
  username: {{ .Values.auth.username | b64enc | quote }}
  password: {{ .Values.auth.password | b64enc | quote }}
  database: {{ .Values.auth.database | b64enc | quote }}