apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb
  labels:
    app: mongodb
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: mongodb
  selector:
    app: mongodb
    release: {{ .Release.Name }}